# Generated by Django 2.2.5 on 2019-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0002_auto_20190929_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='space',
            field=models.IntegerField(default=3),
        ),
    ]
