# Generated by Django 2.2.5 on 2019-09-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0003_auto_20190929_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shuttle.Driver'),
        ),
    ]
