# Generated by Django 2.2.5 on 2019-09-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0007_auto_20190929_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='route',
            field=models.URLField(blank=True, null=True),
        ),
    ]
