# Generated by Django 2.2.5 on 2019-09-29 21:18

from django.db import migrations, models
import django.utils.crypto
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0008_shuttle_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='token',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
