# Generated by Django 2.2.5 on 2019-09-29 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0009_auto_20190929_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='nick',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
