# Generated by Django 2.2.5 on 2019-09-30 09:10

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0010_auto_20190930_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='token',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=12),
        ),
    ]
